#!/bin/sh
reset="\033[0m"
red="\033[1;31m" # red
orange="\x1b[38;2;255;106;0m" # orange
yellow="\033[1;33m" # yellow
green="\033[1;32m" # green
lblue="\033[1;96m" # light blue
blue="\033[1;34m" # blue
purple="\033[1;35m" # purple
aqua="\033[1;36m" # aqua
gray="\033[38;2;106;106;106m" # gray
userg=$(whoami) 
host=$(uname -n)  
shell=$(basename $0)

distrog(){
    if [ "$(uname -s)" = "FreeBSD" ]; then
        if [ -d /System ]; then
            echo "Hellosystem"
        else
            echo "FreeBSD"
        fi
    elif [ "$(uname -s)" = "OpenBSD" ]; then
        echo "OpenBSD"
    elif [ "$(uname -s)" = "NetBSD" ]; then
        echo "NetBSD"
    elif [ -f "/etc/os-release" ]; then
        cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}' | tr -d '"'
    elif command -v getprop >/dev/null 2>&1; then
        echo "Android $(getprop ro.build.version.release)"
    elif [ "$(uname -s)" = "Haiku" ]; then
        echo "HaikuOS"
    else
        echo "Unknown"
    fi
}

case "$(distrog)" in
        "EndeavourOS"*) ascii="endeavouros" ;;
        "Void Linux"*) ascii="void" ;;
        "Ubuntu"*) ascii="ubuntu" ;;
        "Debian"*) ascii="debian" ;;
        "Arch Linux"*) ascii="arch" ;;
        "Linux Mint"*) ascii="mint" ;;
        "NixOS"*) ascii="nixos" ;;
        "Alpine Linux"*) ascii="alpine" ;;
        "Fedora Linux"*) ascii="fedora" ;;
        "PostmarketOS"*) ascii="pmos" ;;
        "CRUX"|"KISS"*) ascii="crux" ;;
        "openSUSE"*) ascii="opensuse" ;;
        "Locoware GNU/Linux"*) ascii="locoware" ;;
        "Artix"*) ascii="artix" ;;
        "Slackware"*) ascii="slackware" ;;
        "Devuan GNU/Linux"*) ascii="devuan" ;;
        FreeBSD|Hellosystem*) ascii="freebsd" ;;
        "Gentoo"*) ascii="gentoo" ;;
        "Android"*) ascii="android" ;;
        "CachyOS"*) ascii="cachy" ;;
        "Pop!_OS"*) ascii="pop" ;;
        "OpenBSD"*) ascii="openbsd" ;;
        "NetBSD"*) ascii="netbsd" ;;
        "CentOS"*) ascii="centos" ;;
        "Haiku"*) ascii="haiku" ;;
        "Venom GNU/Linux"*) ascii="venom" ;;
        *) ascii="unknown" ;;  
esac

# thanks to locomia
for arg in "$@"; do
    case "$arg" in
        --ascii=*) ascii=$(echo "$arg" | cut -d= -f2) ;;
        --nocol*)
                reset=""
                red=""
                orange=""
                yellow=""
                green=""
                lblue=""
                blue=""
                purple=""
                aqua=""
                gray=""
                color=""
            ;;
        --help*) 
            echo "--ascii <ascii> sets ascii"
            echo "--nocol removes color"
            ;;
    esac
done

# if you wanna add your custom(working ofc) pkg manager, then type:
# elif command -v <pkg manager> >/dev/null 2>&1; then
#   echo "<pkg manager> [$(<command to count packages>)]"
# elif
# ...
pkgm(){
    if command -v pacman >/dev/null 2>&1; then
        echo "pacman [$(pacman -Qq | wc -l)]"
    elif command -v apt >/dev/null 2>&1; then
        echo "apt [$(dpkg --get-selections | grep -v deinstall | wc -l)]"
    elif command -v dnf >/dev/null 2>&1; then
        echo "dnf [$(rmp -qa | wc -l)]"
    elif command -v zypper >/dev/null 2>&1; then
        echo "zypper [$(rpm -qa | wc -l)]"
    elif command -v apk >/dev/null 2>&1; then
        echo "apk [$(grep -c '^P:' /lib/apk/db/installed)]"
    elif command -v xbps-install >/dev/null 2>&1; then
        echo "xbps [$(xbps-query -l | wc -l)]"
    elif command -v pkg >/dev/null 2>&1; then
        if [ "$(uname -o)" = "FreeBSD" ]; then
            echo "pkg [$(pkg query -a '%n' | wc -l | tr -d ' ')]"
        elif [ "$(uname -s)" = "Darwin" ]; then
            echo "pkg [$(pkg list | wc -l | tr -d ' ')]"
        fi
    elif command -v nix >/dev/null 2>&1; then
        echo "nix"
    elif command -v scoop >/dev/null 2>&1; then
        echo "scoop"
    elif command -v pkgtool >/dev/null 2>&1; then
        echo "pkgtool [$(ls /var/log/packages | wc -l)]"
    elif command -v yum >/dev/null 2>&1; then
        echo "yum [$(rpm -qa | wc -l)]"
    elif command -v emerge >/dev/null 2>&1; then
        echo "emerge [$(qlist -I | wc -l)]"
    elif command -v prt-get >/dev/null 2>&1; then
        echo "prt-get [$(pkginfo -i | wc -l)]"
    elif command -v scratch >/dev/null 2>&1; then
        echo "scratch [$(ls /var/lib/scratchpkg/db/ | wc -l)]"
    elif command -v pkg_add >/dev/null 2>&1; then
        if [ "$(uname -s)" = "OpenBSD" ]; then
            echo "pkg_add [$(pkg_info | wc -l | awk '{print $1}')]"
        elif [ "$(uname -s)" = "NetBSD" ]; then
            echo "pkg_add [$(pkg_info | wc -l | awk '{print $1}')]"
        fi
    elif command -v pkgman >/dev/null 2>&1; then
        echo "pkgman [$(find /boot/system/packages /boot/home/config/packages -name "*.hpkg" | wc -l)]"
    elif command -v kiss >/dev/null 2>&1; then
        echo "kiss [$(ls /var/db/kiss/installed | wc -l)]"
    else
        echo "unknown"
    fi
}

# to add your unsupported environment, add this:
# elif pgrep -x <env process> >/dev/null 2>&1; then echo "<env name>"
# elif ...
env() {
    if [ -n "$XDG_CURRENT_DESKTOP" ]; then echo "$XDG_CURRENT_DESKTOP"
    elif [ -n "$DESKTOP_SESSION" ]; then echo "$DESKTOP_SESSION"
    elif pgrep -x xfce4-session >/dev/null 2>&1; then echo "xfce"
    elif pgrep -x gnome-session >/dev/null 2>&1; then echo "gnome"
    elif pgrep -x kdeinit5 >/dev/null 2>&1; then echo "kde"
    elif pgrep -x lxsession >/dev/null 2>&1; then echo "lxde"
    elif pgrep -x mate-session >/dev/null 2>&1; then echo "mate"
    elif pgrep -x sway >/dev/null 2>&1; then
    # i did it cuz one sway user asked me to do this
        if sway --version 2>/dev/null | grep -q 'swayfx'; then
            echo "swayfx"
        else
            echo "sway"
        fi
    elif pgrep -x hyprland >/dev/null 2>&1; then echo "hyprland"
    elif pgrep -x dwm >/dev/null 2>&1; then echo "dwm"
    elif pgrep -x dwl >/dev/null 2>&1; then echo "dwl"
    elif pgrep -x twm >/dev/null 2>&1; then echo "twm"
    elif pgrep -x i3 >/dev/null 2>&1; then echo "i3"
    elif pgrep -x bspwm >/dev/null 2>&1; then echo "bspwm"
    elif pgrep -x herbstluftwm >/dev/null 2>&1; then echo "herbstluftwm"
    elif pgrep -x xmonad >/dev/null 2>&1; then echo "xmonad"
    elif [ pgrep -x niri >/dev/null 2>&1 ] || [ pgrep -x niri-session >/dev/null 2>&1 ]; then echo "niri"
    elif command -v getprop >/dev/null 2>&1; then echo "surfaceflinger"
    elif [ "$(uname -s)" = "Haiku" ]; then echo "tracker"
    elif pgrep -x kwin_x11 >/dev/null 2>&1; then echo "kwin"
    elif tty -s; then echo "tty"
    else echo "Unknown"
    fi
}

ramd(){
    if [ "$(uname -s)" = "FreeBSD" ]; then
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(($(sysctl -n vm.stats.vm.v_wire_count) * pagesi / 1024 / 1024))"
        activm=$(($(sysctl -n vm.stats.vm.v_active_count) * pagesi / 1024 / 1024))
        inactm=$(($(sysctl -n vm.stats.vm.v_inactive_count) * pagesi / 1024 / 1024))
        usedm=$((wiredm + activm + inactm))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
    elif [ "$(uname -s)" = "OpenBSD" ] || [ "$(uname -s)" = "NetBSD" ]; then
        # i dont know how to make it work T_T
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(vmstat -s | grep "pages wired" | awk '{print $1}')"
        activm=$(vmstat -s | grep "pages active" | awk '{print $1}')
        inactm=$(vmstat -s | grep "pages inactive" | awk '{print $1}')
        usedm=$(((wiredm + activm) * pagesi / 1024 / 1024))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
    elif [ "$(uname -s)" = "Haiku" ]; then
        totalmem="$(($(vmstat | grep "max memory" | awk '{print int($3 / 1024 / 1024)}')))"
        usedmem="$(((totalmem - $(vmstat | grep "free memory" | awk '{print int($3 / 1024 / 1024)}'))))"
        echo "${usedmem}MiB / ${totalmem}MiB"
    else
        # i made it cuz environmentingonment bot doesn't have free command
        memtot="$(($(cat /proc/meminfo | awk 'NR==1 {print $2}') / 1024))"
        memavb="$(cat /proc/meminfo | awk 'NR==3 {print $2}')"
        memusd="$(((memtot) - (memavb / 1024)))"
        echo "${memusd}MiB / ${memtot}MiB"
        #free | awk 'NR==2 {print int($3 / 1024)"MiB" " / " int($2 / 1024)"MiB"}'
    fi
}

cpug(){
    if [ "$(uname -s)" = "FreeBSD" ]; then 
        sysctl -n hw.model 2>/dev/null
    elif [ "$(uname -s)" = "OpenBSD" ] || [ "$(uname -s)" = "NetBSD" ]; then 
        sysctl -n hw.model 2>/dev/null
    elif command -v getprop >/dev/null 2>&1; then
        cat /proc/cpuinfo | grep -i 'hardware' | awk -F': ' '{print $2}'
    elif [ "$(uname -s)" = "Haiku" ]; then
        sysinfo -cpu | awk -F '\"' '/CPU #0/ {print $2}'
    else
        grep -m 1 'model name' /proc/cpuinfo | cut -d ':' -f2 | sed 's/^ //'
    fi
}

disk(){
    if command -v getprop >/dev/null 2>&1; then
        df /data -h | awk 'NR==2 {print $3 " / " $2}'
    elif [ "$(uname -s)" = "Haiku" ]; then
        disktotal="$(df /boot | grep "Total Blocks" | awk '{print int($3)}')"
        diskused="$(((disktotal - $(df /boot | grep "Free Blocks" | awk '{print int($3)}'))))"
        echo "${diskused}GiB / ${disktotal}GiB"
    else
        df -h / | awk 'NR==2 {print $3 " / " $2}' 
    fi
}

case "$ascii" in
    endeavouros)
        ascia="${reset}                       "
        ascib="${red}           /${purple}o${blue}.         "
        ascic="${red}         /${purple}sssso${blue}-       "
        ascid="${red}       /${purple}ossssssso${blue}:     "
        ascie="${red}     /${purple}ssssssssssso${blue}+    "
        ascif="${red}   /${purple}ssssssssssssssso${blue}+  "
        ascig="${red} //${purple}osssssssssssssso${blue}+-  "
        ascih="${blue}  \`+++++++++++++++-\`   "
        ascij="                       "
        color="$purple"
        ;;
    mint|linuxmint)
        ascia="${green}  ___________   "
        ascib="${green} |_          \\\  "
        ascic="${green}   | ${reset}| _____${green} |  "
        ascid="${green}   |${reset} | | | | ${green}|  "
        ascie="${green}   |${reset} | | | | ${green}|  "
        ascif=" ${green}  |${reset} \\\_____/ ${reset}${green}|  "
        ascig="${green}   \\\_________/  "
        ascih="                "
        ascij="                "
        color="$green"
        ;;
    slackware|шлака)
        ascia="${blue}    ________   "
        ascib="${blue}   /  ______|  "
        ascic="${blue}   | |______   "
        ascid="${blue}   \\\______  \\\  "
        ascie="${blue}    ______| |  "
        ascif="${blue} | |________/  "
        ascig="${blue} |____________ "
        ascih="               "
        ascij="               "
        color="$blue"
        ;;
    arch)
        ascia="                 " 
        ascib="${lblue}       /\\\        "
        ascic="${lblue}      /  \\\       "
        ascid="${lblue}     /.   \\\      "
        ascie="${lblue}    /      \\\     "
        ascif="${lblue}   /   ,,   \\\    "
        ascig="${lblue}  /   |  |  '\\\   "
        ascih="${lblue} /_-''    ''-_\\\  "
        ascij="                 "
        color="$lblue"
        ;;
    nixos|nix)
        ascia="                 "
        ascib="${lblue}    \\\\\\\  \\\\\\\ //    "
        ascic=" ${lblue}  ==\\\\\\\__\\\\\\\/ //  "
        ascid="${lblue}     //   \\\\\\\//   "
        ascie="${lblue}  ==//     //==  "
        ascif="${lblue}   //\\\\\\\___//     "
        ascig="${lblue}  // /\\\\\\\  \\\\\\\==   "
        ascih="${lblue}    // \\\\\\\  \\\\\\\    " 
        ascij="                "
        color="$lblue"
        ;;
    void|voidlinux)
        ascia="${green}     ________    "
        ascib="${green}   _ \\\_____  \`.  " 
        ascic="${green}  | \\\  ___ \`. |  " 
        ascid="${green}  | | /   \\\ | |  "
        ascie="${green}  | | \\\___/ | |  "
        ascif="${green}  | '._____ \\\_|  "
        ascig="${green}  '._______\\\     "
        ascih="${green}                 "
        ascij="${green}                 "
        color="$green"
        ;;
    ubuntu)
        ascia="              "
        ascib="${orange}          _   "
        ascic="${orange}      ---(_)  "  
        ascid="${orange}  _/  ---  \\\  "
        ascie="${orange} (_) |   |    "
        ascif="${orange}   \\\  --- _/  "
        ascig="${orange}      ---(_)  "
        ascih="              "
        ascij="              "
        color="$orange"
        ;;
    debian)
        # i made this ascii by myself
        ascia="${red}      _,_     "
        ascib="${red}   .:'\`\`\`':.  "
        ascic="${red}  ::   _  ':  " 
        ascid="${red}  ::  :   .:  "
        ascie="${red}  ':   \`\"'\`   " 
        ascif="${red}   \`:,        "
        ascig="${red}     \`\":,     "
        ascih="${red}              "
        ascij="${red}              "
        color="$red"
        ;;
    alpine|alpinelinux)
        ascia="                "
        ascib="${blue}     /\\\ /\\\      "
        ascic="${blue}    // \\\  \\\     "
        ascid="${blue}   //   \\\  \\\    "
        ascie="${blue}  //     \\\  \\\   "
        ascif="${blue} //       \\\  \\\  "
        ascig="${blue}           \\\  \\ "
        ascih="${blue}            \\\   "
        ascij="                "
        color="$blue"
        ;;
    fedora)
        ascia="${blue}                 "
        ascib="${blue}         .###.   "
        ascic="${blue}        #'   '#  "
        ascid="${blue}        W     '  "
        ascie="${blue}   .w##A&##'     "
        ascif="${blue}  #'    M        "
        ascig="${blue}  #,   ,#        "
        ascih="${blue}  \`*###*'        "
        ascij="${blue}                 "
        color="$blue"
        ;;
    pmos|postmarketos)
        ascia="              "
        ascib="${green}      /\\\      "
        ascic="${green}     /  \\\     "
        ascid="${green}     \\\_  \\\    "
        ascie="${green}   /\\\_ \\\/ _   "
        ascif="${green}  /  / __/ \\\  "
        ascig="${green} /___\\\ \\\____\\\ "
        ascih="              "
        ascij="              "
        color="$green"
        ;;
    crux|CRUX|kiss|KISS)
        ascia="${blue}      ___     "
        ascib="${blue}     (${reset}..${blue} |    "
        ascic="${blue}     (${purple}<>${blue} |    "
        ascid="${blue}    / ${reset}__${blue}  \\\   "
        ascie="${blue}   ( ${reset}/  \\\\${blue} /|  "
        ascif="${blue}  ${purple}_${blue}/\\\\${reset} __)${blue}/${purple}_${blue})  "
        ascig="${blue}  ${purple}\\\/${blue}-____${purple}\\\/   "
        ascih="              "
        ascij="              "
        color="$blue"
        ;;
    opensuse)
        ascia="${green}     _______    "
        ascib="${green}  __|    __ \\\   "
        ascic="${green} |      / .\\\ \\\  "
        ascid="${green} |      \\\__/ |  "
        ascie="${green} |    _______|  "
        ascif="${green} |    \\\_______  "
        ascig="${green} |___________/  "
        ascih="${green}                "
        ascij="${green}               "
        color="$green"
        ;;
    locoware)
        ascia="              "
        ascib="              "
        ascic="${yellow}       dMP    "
        ascid="${yellow}      dMP     "
        ascie="${yellow}     dMP      "
        ascif="${yellow}    dMP       "
        ascig="${yellow}   dMMMMMMP   "
        ascih="              "
        ascij="              "
        color="$yellow"
        ;;
    artix)
        ascia="                "
        ascib="${lblue}       /\\\       "
        ascic="${lblue}      /  \\\      "
        ascid="${lblue}     /\`'.,\\\     "
        ascie="${lblue}    /     ',    "
        ascif="${lblue}   /      ,\`\\\   "
        ascig="${lblue}  /   ,.'\`.  \\\  "
        ascih="${lblue} /.,'\`     \`'.\\\ "
        ascij="                "
        color="$lblue"
        ;;
    devuan)
        ascia="                "
        ascib="${yellow}   ..:::.       "
        ascic="${yellow}      ''===-    "
        ascid="${yellow}          '+#;  "
        ascie="${yellow}           =##  "
        ascif="${yellow}       .+:##;   "
        ascig="${yellow}  .:=+###:*'    "
        ascih="${yellow}  '####='       "
        ascij="                "
        color="$yellow"
        ;;
    freebsd|hellosystem)
        ascia="                 "
        ascib="${red}  /\\\,-'''''-,/\\\  "
        ascic="${red}  \\\_)       (_/  "
        ascid="${red}  |           |  "
        ascie="${red}  |           |  "
        ascif="${red}   ;         ;   "
        ascig="${red}    '-_____-'    "
        ascih="                 "
        ascij="                 "
        color="$red"
        ;;
    gentoo)
        ascia="${purple}   _-----_     "
        ascib="${purple}  (       \\\    "
        ascic="${purple}  \\\    0   \\\   "
        ascid="${reset}   \\\        )  "
        ascie="${reset}   /      _/   "
        ascif="${reset}  (     _-     "
        ascig="${reset}  \\\____-       "
        ascih="               "
        ascij="               "
        color="$purple"
        ;;
    android)
        ascia="                     "
        ascib="${green}   ;,           ,;   "
        ascic="${green}    ';,.-----.,;'    "
        ascid="${green}   ,'           ',   "
        ascie="${green}  /    O     O    \\\  "
        ascif="${green} |                 | "
        ascig="${green} '-----------------' "
        ascih="                     "
        ascij="                     "
        color="$green"
        ;;
    cachy|cachyos)
        ascia="${aqua}    .::::::::::::'    "
        ascib="${aqua}   .::::::::::::'     "
        ascic="${aqua}  .::::::'            "
        ascid="${aqua} .::::::'             "
        ascie="${aqua} '::::::.             "
        ascif="${aqua}  '::::::.            "
        ascig="${aqua}   '::::::::::::::::' "
        ascih="${aqua}    '::::::::::::::'  "
        ascij="                     "
        color="$aqua"
        ;;
    pop|popos)
        ascia="${aqua}  ______             "
        ascib="${aqua}  \\\   _ \\\        __  "
        ascic="${aqua}   \\\ \ \\\ \\\      / /  "
        ascid="${aqua}    \\\ \\\_\\\ \\\    / /   "
        ascie="${aqua}     \\\  ___\\\  /_/    "
        ascif="${aqua}      \\\ \\\    _       " 
        ascig="${aqua}     __\\\ \\\__(_)_     "
        ascih="${aqua}    (___________)    "
        ascij="                   "
        color="$aqua"
        ;;
    openbsd)
        ascia="${yellow}        _____      "
        ascib="${yellow}      \\\-     -/    "
        ascic="${yellow}   \\\_/         \\\   "
        ascid="${yellow}   |        ${reset}O O${yellow} |  "
        ascie="${yellow}   |_  <   )  3 )  "
        ascif="${yellow}   / \\\         /   "
        ascig="${yellow}      /-_____-\\\    "
        ascih="${yellow}                   "
        ascij="                  "
        color="$yellow"
        ;;
    centos)
        ascia="               "
        ascib="   ${green}____${yellow}^${purple}____   "
        ascic="   ${green}|\\\  ${yellow}|${purple}  /|   "
        ascid="   ${green}| \\\ ${yellow}|${purple} / |   "
        ascie="  ${purple}<---- ${lblue}---->  "
        ascif="   ${lblue}| / ${green}|${yellow} \\\ |   "
        ascig="   ${lblue}|/__${green}|${yellow}__\\\|   "
        ascih="       ${green}v       "
        ascij="               "
        color="$green"
        ;;
    netbsd)
        ascia="  \\\\\\\\${red}\`-______,----__    "
        ascib="   \\\\\\\ ${red}       __,---\`_  "
        ascic="    \\\\\\\ ${red}      \`.____    "
        ascid="     \\\\\\\\${red}-______,----\`-  "
        ascie="      \\\\\\\               "
        ascif="       \\\\\\\              "
        ascig="        \\\\\\\             "
        ascih="         \\\\\\\            "
        ascij="                     "
        color="$red"
        ;;
    haiku|haikuos)
        ascia="${green}         ,^,         "
        ascib="${green}        /   \\\        "
        ascic="${green}  *--_ ;     ; _--*  "
        ascid="${green}  \\\   '\"     \"'   /  "
        ascie="${green}   '.           .'   "
        ascif="${green}  .-'\"         \"'-.  "
        ascig="${green}   '-.__.   .__.-'   "
        ascih="${green}         |_|         "
        ascij="                     "
        color="$green"
        ;;
    venom|venomlinux)
        ascia="${gray}  ,__   _,.,_       "
        ascib="${gray}  ':###:\"'\`'\"#:.    "
        ascic="${gray}    :####.    '#:   "
        ascid="${gray}   :#: '####.  :#:  "
        ascie="${gray}    :#.   '###.#:   "
        ascif="${gray}     '#:,,_,,:###:  "
        ascig="${gray}       \`''=''\` '^:  "
        ascih="                    "
        ascij="                   "
        color="$gray"
        ;;
    *)
        ascia="     ___     "
        ascib="    (.. |    "
        ascic="    (<> |    "
        ascid="   / __  \\\   "
        ascie="  ( /  \\\ /|  "
        ascif=" _/\\\ __)/_)  "
        ascig=" \\\/-____\\\/   "
        ascih="             "
        ascij="             "
        ;;
esac

printf "\n"
printf "%s$ascia $reset ${color}$userg${reset}@${color}$host${reset} \n"
printf "%s$ascib $reset ${color}os:${reset}     $(distrog)\n"
printf "%s$ascic $reset ${color}pkg:${reset}    $(pkgm)\n"
printf "%s$ascid $reset ${color}ram:${reset}    $(ramd)\n"
printf "%s$ascie $reset ${color}cpu:${reset}    $(cpug)\n"
printf "%s$ascif $reset ${color}sh:${reset}     $shell\n"
printf "%s$ascig $reset ${color}env:${reset}    $(env)\n"
printf "%s$ascih $reset ${color}disk:${reset}   $(disk)\n"
printf "%s$ascij\n"
