#!/bin/sh
res="\033[0m"
c1="\033[1;31m" # red
c2="\x1b[38;2;255;106;0m" # orange
c3="\033[1;33m" # yellow
c4="\033[1;32m" # green
c5="\033[1;96m" # light blue
c6="\033[1;34m" # blue
c7="\033[1;35m" # purple
c8="\033[1;36m" # aqua
c9="\033[1;37m" # gray or white
userg=$(id -un) # username
host=$(uname -n) # hostname
shell=$(basename $SHELL)

distrog(){
    if [ "$(uname -s)" = "FreeBSD" ]; then
        echo "FreeBSD"
    elif [ "$(uname -s)" = "OpenBSD" ]; then
        echo "OpenBSD"
    elif [ "$(uname -s)" = "NetBSD" ]; then
        echo "NetBSD"
    elif command -v getprop >/dev/null 2>&1; then
        echo "Android $(getprop ro.build.version.release)"
    else
        cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}' | tr -d '"'
    fi
}

case "$(distrog)" in
        "EndeavourOS"*) ascii="endeavouros"; color="$c7" ;;
        "Void Linux"*) ascii="void"; color="$c4" ;;
        "Ubuntu"*) ascii="ubuntu"; color="$c2" ;;
        "Debian"*) ascii="debian"; color="$c1" ;;
        "Arch Linux"*) ascii="arch"; color="$c5" ;;
        "Linux Mint"*) ascii="mint"; color="$c4" ;;
        "NixOS"*) ascii="nixos"; color="$c5" ;;
        "Alpine Linux"*) ascii="alpine"; color="$c5" ;;
        "Fedora Linux"*) ascii="fedora"; color="$c6" ;;
        "PostmarketOS"*) ascii="pmos"; color="$c4" ;;
        "CRUX"*) ascii="crux"; color="$c6" ;;
        "openSUSE"*) ascii="opensuse"; color="$c4" ;;
        "Locoware GNU/Linux"*) ascii="locoware"; color="$c3" ;;
        "Artix"*) ascii="artix"; color="$c5" ;;
        "Slackware"*) ascii="slackware"; color="$c6" ;;
        "Devuan GNU/Linux"*) ascii="devuan"; color="$c3" ;;
        "FreeBSD"*) ascii="freebsd"; color="$c1" ;;
        "Gentoo"*) ascii="gentoo"; color="$c7" ;;
        "Android"*) ascii="android"; color="$c4" ;;
        "CachyOS"*) ascii="cachy"; color="$c8" ;;
        "Pop!_OS"*) ascii="pop"; color="$c8" ;;
        "OpenBSD"*) ascii="openbsd"; color="$c3" ;;
        "NetBSD"*) ascii="netbsd"; color="$c1" ;;
        "CentOS"*) ascii="centos"; color="$c4" ;;
        *) ascii="crux" ;;  
esac

# thanks to locomia
for arg in "$@"; do
    case "$arg" in
        --ascii=*) ascii=$(echo "$arg" | cut -d= -f2) ;;
        --nocol=*)
            if [ "$(echo $arg | cut -d= -f2)" = "true" ]; then
                res=""
                c1=""
                c2=""
                c3=""
                c4=""
                c5=""
                c6=""
                c7=""
                c8=""
                c9=""
                color=""
            else
                echo
            fi
            ;;
    esac
done

# if you wanna add your custom(working ofc) pkg manager, then type:
# elif command -v <pkg manager> >/dev/null 2>&1; then
#   echo "<pkg manager> [$(<command to count packages>)]"
# elif
# ...
pkgm(){
    if command -v pacman >/dev/null 2>&1; then
        echo "pacman [$(pacman -Qq | wc -l)]"
    elif command -v apt >/dev/null 2>&1; then
        echo "apt [$(dpkg --get-selections | grep -v deinstall | wc -l)]"
    elif command -v dnf >/dev/null 2>&1; then
        echo "dnf [$(rmp -qa | wc -l)]"
    elif command -v zypper >/dev/null 2>&1; then
        echo "zypper [$(rpm -qa | wc -l)]"
    elif command -v apk >/dev/null 2>&1; then
        echo "apk [$(grep -c '^P:' /lib/apk/db/installed)]"
    elif command -v xbps-install >/dev/null 2>&1; then
        echo "xbps [$(xbps-query -l | wc -l)]"
    elif command -v pkg >/dev/null 2>&1; then
        if [ "$(uname -o)" = "FreeBSD" ]; then
            echo "pkg [$(pkg query -a '%n' | wc -l | tr -d ' ')]"
        elif [ "$(uname -s)" = "Darwin" ]; then
            echo "pkg [$(pkg list | wc -l | tr -d ' ')]"
        fi
    elif command -v nix >/dev/null 2>&1; then
        echo "nix"
    elif command -v scoop >/dev/null 2>&1; then
        echo "scoop"
    elif command -v pkgtool >/dev/null 2>&1; then
        echo "pkgtool [$(ls /var/log/packages | wc -l)]"
    elif command -v yum >/dev/null 2>&1; then
        echo "yum [$(rpm -qa | wc -l)]"
    elif command -v emerge >/dev/null 2>&1; then
        echo "emerge [$(qlist -I | wc -l)]"
    elif command -v prt-get >/dev/null 2>&1; then
        echo "prt-get [$(pkginfo -i | wc -l)]"
    elif command -v scratch >/dev/null 2>&1; then
        echo "scratchpkg [$(scratch list-installed | wc -l)]"
    elif command -v pkg_add >/dev/null 2>&1; then
        echo "pkg_add [$(pkg_info | wc -l | awk '{print $1}')]"
    else
        echo "unknown"
    fi
}

# to add your unsupported environment, add this:
# elif pgrep -x <env process> >/dev/null 2>&1; then echo "<env name>"
# elif ...
env() {
    if [ -n "$XDG_CURRENT_DESKTOP" ]; then echo "$XDG_CURRENT_DESKTOP"
    elif [ -n "$DESKTOP_SESSION" ]; then echo "$DESKTOP_SESSION"
    elif pgrep -x xfce4-session >/dev/null 2>&1; then echo "xfce"
    elif pgrep -x gnome-session >/dev/null 2>&1; then echo "gnome"
    elif pgrep -x kdeinit5 >/dev/null 2>&1; then echo "kde"
    elif pgrep -x lxsession >/dev/null 2>&1; then echo "lxde"
    elif pgrep -x mate-session >/dev/null 2>&1; then echo "mate"
    elif pgrep -x sway >/dev/null 2>&1; then
    # i did it cuz one sway user asked me to do this
        if sway --version 2>/dev/null | grep -q 'swayfx'; then
            echo "swayfx"
        else
            echo "sway"
        fi
    elif pgrep -x hyprland >/dev/null 2>&1; then echo "hyprland"
    elif pgrep -x dwm >/dev/null 2>&1; then echo "dwm"
    elif pgrep -x twm >/dev/null 2>&1; then echo "twm"
    elif pgrep -x i3 >/dev/null 2>&1; then echo "i3"
    elif pgrep -x bspwm >/dev/null 2>&1; then echo "bspwm"
    elif pgrep -x herbstluftwm >/dev/null 2>&1; then echo "herbstluftwm"
    elif pgrep -x xmonad >/dev/null 2>&1; then echo "xmonad"
    elif command -v getprop >/dev/null 2>&1; then echo "surfaceflinger"
    elif tty -s; then echo "tty"
    else echo "Unknown"
    fi
}

ramd(){
    if [ "$(uname -s)" = "FreeBSD" ]; then
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(($(sysctl -n vm.stats.vm.v_wire_count) * pagesi / 1024 / 1024))"
        activm=$(($(sysctl -n vm.stats.vm.v_active_count) * pagesi / 1024 / 1024))
        inactm=$(($(sysctl -n vm.stats.vm.v_inactive_count) * pagesi / 1024 / 1024))
        usedm=$((wiredm + activm + inactm))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
    elif [ "$(uname -s)" = "OpenBSD" ] || [ "$(uname -s)" = "NetBSD" ]; then
        # i dont know how to make it work T_T
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(vmstat -s | grep "pages wired" | awk '{print $1}')"
        activm=$(vmstat -s | grep "pages active" | awk '{print $1}')
        inactm=$(vmstat -s | grep "pages inactive" | awk '{print $1}')
        usedm=$(((wiredm + activm) * pagesi / 1024 / 1024))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
    else
        # i made it cuz environmentingonment bot doesn't have free command
        memtot="$(($(cat /proc/meminfo | awk 'NR==1 {print $2}') / 1024))"
        memavb="$(cat /proc/meminfo | awk 'NR==3 {print $2}')"
        memusd="$(((memtot) - (memavb / 1024)))"
        echo "${memusd}MiB / ${memtot}MiB"
        #free | awk 'NR==2 {print int($3 / 1024)"MiB" " / " int($2 / 1024)"MiB"}'
    fi
}

cpug(){
    if [ "$(uname -s)" = "FreeBSD" ]; then 
        sysctl -n hw.model 2>/dev/null
    elif [ "$(uname -s)" = "OpenBSD" ] || [ "$(uname -s)" = "NetBSD" ]; then 
        sysctl -n hw.model 2>/dev/null
    elif command -v getprop >/dev/null 2>&1; then
        cat /proc/cpuinfo | grep -i 'hardware' | awk -F': ' '{print $2}'
    else
        grep -m 1 'model name' /proc/cpuinfo | cut -d ':' -f2 | sed 's/^ //'
    fi
}

disk(){
    if command -v getprop >/dev/null 2>&1; then
        df -h /data | awk 'NR==2 {print $3 " / " $2}'
    else
        df -h / | awk 'NR==2 {print $3 " / " $2}' 
    fi
}

case "$ascii" in
    endeavouros*)
        ascia="${res}                       "
        ascib="${c1}           /${c7}o${c6}.         "
        ascic="${c1}         /${c7}sssso${c6}-       "
        ascid="${c1}       /${c7}ossssssso${c6}:     "
        ascie="${c1}     /${c7}ssssssssssso${c6}+    "
        ascif="${c1}   /${c7}ssssssssssssssso${c6}+  "
        ascig="${c1} //${c7}osssssssssssssso${c6}+-  "
        ascih="${c6}  \`+++++++++++++++-\`   "
        ascij="                       "
        ;;
    mint*)
        ascia="                 "
        ascib="${c4}  ___________    "
        ascic="${c4} |_          \\\   "
        ascid="${c4}   | |${res} _____${c4} |   "
        ascie="${c4}   |${res} | | | | ${c4}|   "
        ascif="${c4}   |${res} | | | | ${c4}|   "
        ascig=" ${c4}  |${res} \\\_____/ ${res}${c4}|   "
        ascih="${c4}   \\\_________/   "
        ascij="                 "
        ;;
    slackware*)
        ascia="               "
        ascib="${c6}    ________   "
        ascic="${c6}   /  ______|  "
        ascid="${c6}   | |______   "
        ascie="${c6}   \\\______  \\\  "
        ascif="${c6}    ______| |  "
        ascig="${c6} | |________/  "
        ascih="${c6} |____________ "
        ascij="               "
        ;;
    arch*)
        ascia="                 " 
        ascib="${c5}       /\\\        "
        ascic="${c5}      /  \\\       "
        ascid="${c5}     /    \\\      "
        ascie="${c5}    /      \\\     "
        ascif="${c5}   /   ,,   \\\    "
        ascig="${c5}  /   |  |   \\\   "
        ascih="${c5} /_-''    ''-_\\\  "
        ascij="                 "
        ;;
    nixos*)
        ascia="                "
        ascib="${c5}    \\\\\\\  \\\\\\\ //    "
        ascic=" ${c5}  ==\\\\\\\__\\\\\\\/ //  "
        ascid="${c5}     //   \\\\\\\//   "
        ascie="${c5}  ==//     //==  "
        ascif="${c5}   //\\\\\\\___//     "
        ascig="${c5}  // /\\\\\\\  \\\\\\\==   "
        ascih="${c5}    // \\\\\\\  \\\\\\\    " 
        ascij="                "
        ;;
    void*)
        ascia="${c4}    ________    "
        ascib="${c4}  _ \\\______ \\\   "
        ascic="${c4} | \\\  ___  \\\ |  "
        ascid="${c4} | | /   \\\ | |  " 
        ascie="${c4} | | \\\___/ | |  " 
        ascif="${c4} | \\\______ \\\_|  "
        ascig="${c4}  \\\_______\\\     "
        ascih="                "
        ascij="                "
        ;;
    ubuntu*)
        ascia="              "
        ascib="${c2}          _   "
        ascic="${c2}      ---(_)  "  
        ascid="${c2}  _/  ---  \\\  "
        ascie="${c2} (_) |   |    "
        ascif="${c2}   \\\  --- _/  "
        ascig="${c2}      ---(_)  "
        ascih="              "
        ascij="              "
        ;;
    debian*)
        ascia="           "
        ascib="${c1}   _____   "
        ascic="${c1}  /  __ \\\  "
        ascid="${c1} |  /    | "
        ascie="${c1} |  \\\___-  " 
        ascif="${c1} -_        "
        ascig="${c1}   --_     "
        ascih="           "
        ascij="           "
        ;;
    alpine*)
        ascia="${c5}     /\\\ /\\\      "
        ascib="${c5}    // \\\  \\\     "
        ascic="${c5}   //   \\\  \\\    "
        ascid="${c5}  //     \\\  \\\   "
        ascie="${c5} //       \\\  \\\  "
        ascif="${c5}           \\\  \\ "
        ascig="${c5}            \\\   "
        ascih="                "
        ascij="                "
        ;;
    fedora*)
        ascia="${c5}         ,'''''.  "
        ascib="${c5}        |   ,. |  "
        ascic="${c5}        |  |  ''  "
        ascid="${c5}   ,....|  |..    "
        ascie="${c5} .'  ,_;|   ..'   "
        ascif="${c5} |  |   |  |      "
        ascig="${c5} |  ',_,'  |      "
        ascih="${c5} '.       ,'      "
        ascij="${c5}   '''''''        "
        ;;
    pmos*)
        ascia="              "
        ascib="${c4}      /\\\      "
        ascic="${c4}     /  \\\     "
        ascid="${c4}     \\\_  \\\    "
        ascie="${c4}   /\\\_ \\\/ _   "
        ascif="${c4}  /  / __/ \\\  "
        ascig="${c4} /___\\\ \\\____\\\ "
        ascih="              "
        ascij="              "
        ;;
    crux*)
        ascia="             "
        ascib="${c5}     ___     "
        ascic="${c5}    (.· |    "
        ascid="${c5}    (<> |    "
        ascie="${c5}   / __  \\\   "
        ascif="${c5}  ( /  \\\ /|  "
        ascig="${c5} _/\\\ __)/_)  "
        ascih="${c5} \\\/-____\\\/   "
        ascij="            "
        ;;
    opensuse*)
        ascia="${c4}   .oooo.           "
        ascib="${c4}  o   o  o          "
        ascic="${c4}  ooooo  oo         "
        ascid="${c4}  o      oo         "
        ascie="${c4}   'oooooooooooo.   "
        ascif="${c4}         oo      o  "
        ascig="${c4}         oo  ooooo  "
        ascih="${c4}          o  o   o  "
        ascij="${c4}           'oooo'   "
        ;;
    locoware*)
        ascia="              "
        ascib="${c3}       dMP    "
        ascic="${c3}      dMP     "
        ascid="${c3}     dMP      "
        ascie="${c3}    dMP       "
        ascif="${c3}   dMMMMMMP   "
        ascig="              "
        ascih="              "
        ascij="              "
        ;;
    artix*)
        ascia="                "
        ascib="${c5}       /\\\       "
        ascic="${c5}      /  \\\      "
        ascid="${c5}     /\`'.,\\\     "
        ascie="${c5}    /     ',    "
        ascif="${c5}   /      ,\`\\\   "
        ascig="${c5}  /   ,.'\`.  \\\  "
        ascih="${c5} /.,'\`     \`'.\\\ "
        ascij="                "
        ;;
    devuan*)
        ascia="               "
        ascib="${c3}  ..::.        "
        ascic="${c3}     ''===-    "
        ascid="${c3}         '+#;  "
        ascie="${c3}          =##  "
        ascif="${c3}      .+:##;   "
        ascig="${c3} .:=+###:*'    "
        ascih="${c3} '####='       "
        ascij="               "
        ;;
    freebsd*)
        ascia="                "
        ascib="${c1} /\\\,-'''''-,/\\\  "
        ascic="${c1} \\\_)       (_/  "
        ascid="${c1} |           |  "
        ascie="${c1} |           |  "
        ascif="${c1}  ;         ;   "
        ascig="${c1}   '-_____-'    "
        ascih="                "
        ascij="                "
        ;;
    gentoo*)
        ascia="${c7}   _-----_     "
        ascib="${c7}  (       \\\    "
        ascic="${c7}  \\\    0   \\\   "
        ascid="${res}   \\\        )  "
        ascie="${res}   /      _/   "
        ascif="${res}  (     _-     "
        ascig="${res}  \\\____-       "
        ascih="               "
        ascij="               "
        ;;
    android*)
        ascia="                     "
        ascib="${c4}   ;,           ,;   "
        ascic="${c4}    ';,.-----.,;'    "
        ascid="${c4}   ,'           ',   "
        ascie="${c4}  /    O     O    \\\  "
        ascif="${c4} |                 | "
        ascig="${c4} '-----------------' "
        ascih="                     "
        ascij="                     "
        ;;
    cachy*)
        ascia="${c8}    .::::::::::::'    "
        ascib="${c8}   .::::::::::::'     "
        ascic="${c8}  .::::::'            "
        ascid="${c8} .::::::'             "
        ascie="${c8} '::::::.             "
        ascif="${c8}  '::::::.            "
        ascig="${c8}   '::::::::::::::::' "
        ascih="${c8}    '::::::::::::::'  "
        ascij="                     "
        ;;
    pop*)
        ascia="${c8}  ______             "
        ascib="${c8}  \\\   _ \\\        __  "
        ascic="${c8}   \\\ \ \\\ \\\      / /  "
        ascid="${c8}    \\\ \\\_\\\ \\\    / /   "
        ascie="${c8}     \\\  ___\\\  /_/    "
        ascif="${c8}      \\\ \\\    _       " 
        ascig="${c8}     __\\\ \\\__(_)_     "
        ascih="${c8}    (___________)    "
        ascij="                   "
        ;;
    openbsd*)
        ascia="${c3}        _____      "
        ascib="${c3}      \\\-     -/    "
        ascic="${c3}   \\\_/         \\\   "
        ascid="${c3}   |        ${res}O O${c3} |  "
        ascie="${c3}   |_  <   )  3 )  "
        ascif="${c3}   / \\\         /   "
        ascig="${c3}      /-_____-\\\    "
        ascih="${c3}                   "
        ascij="                  "
        ;;
    centos*)
        ascia="               "
        ascib="   ${c4}____${c3}^${c7}____   "
        ascic="   ${c4}|\\\  ${c3}|${c7}  /|   "
        ascid="   ${c4}| \\\ ${c3}|${c7} / |   "
        ascie="  ${c7}<---- ${c5}---->  "
        ascif="   ${c5}| / ${c4}|${c3} \\\ |   "
        ascig="   ${c5}|/__${c4}|${c3}__\\\|   "
        ascih="       ${c4}v       "
        ascij="               "
        ;;
    netbsd*)
        ascia="  \\\\\\\\${c1}\`-______,----__    "
        ascib="   \\\\\\\ ${c1}       __,---\`_  "
        ascic="    \\\\\\\ ${c1}      \`.____    "
        ascid="     \\\\\\\\${c1}-______,----\`-  "
        ascie="      \\\\\\\               "
        ascif="       \\\\\\\              "
        ascig="        \\\\\\\             "
        ascih="         \\\\\\\            "
        ascij="                     "
        ;;
esac

printf "\n"
printf "%s$ascia $res ${color}$userg${res}@${color}$host${res} \n"
printf "%s$ascib $res ${color}os:${res}     $(distrog)\n"
printf "%s$ascic $res ${color}pkg:${res}    $(pkgm)\n"
printf "%s$ascid $res ${color}ram:${res}    $(ramd)\n"
printf "%s$ascie $res ${color}cpu:${res}    $(cpug)\n"
printf "%s$ascif $res ${color}sh:${res}     $shell\n"
printf "%s$ascig $res ${color}de/wm:${res}  $(env)\n"
printf "%s$ascih $res ${color}disk:${res}   $(disk)\n"
printf "%s$ascij\n"
