#!/bin/sh
reset="\033[0m"
red="\033[1;31m" # red
orange="\x1b[38;2;255;106;0m" # orange
yellow="\033[1;33m" # yellow
green="\033[1;32m" # green
lblue="\033[1;96m" # light blue
blue="\033[1;34m" # blue
purple="\033[1;35m" # purple
aqua="\033[1;36m" # aqua
gray="\033[38;2;106;106;106m" # gray 
host=$(uname -n)  
shell=$(basename "$SHELL")
UNAME="$(uname -s)"

userg(){
    if command -v whoami >/dev/null 2>&1; then
        whoami
    else
        id -un
    fi
}

distrog(){
    case "$UNAME" in
        FreeBSD) [ -d /System ] && echo "Hellosystem" || echo "FreeBSD" ;;
        OpenBSD) echo "OpenBSD" ;;
        NetBSD) echo "NetBSD" ;;
        Minix) echo "Minix" ;;
        DragonFly) echo "DragonFly" ;;
        Haiku) echo "Haiku" ;;
        SunOS) cat /etc/release | awk 'NR==1 {print $1}' ;;
        Linux|GNU) 
            if [ -d /bedrock ]; then 
                brl version
            elif [ -f /etc/os-release ]; then
                cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}' | tr -d '"'
            elif command -v getprop >/dev/null 2>&1; then
                echo "Android $(getprop ro.build.version.release)"
            elif [ -f /etc/gobo ]; then
                echo "Gobo Linux $(cat /etc/GoboLinuxVersion)"
            fi
        ;;
        *) echo "Unknown"
    esac
}

ascii=$(distrog)

# thanks to locomia
for arg in "$@"; do
    case "$arg" in
        --ascii=*) ascii=$(echo "$arg" | cut -d= -f2) ;;
        --nocol*)
                reset=""
                red=""
                orange=""
                yellow=""
                green=""
                lblue=""
                blue=""
                purple=""
                aqua=""
                gray=""
                color=""
            ;;
    esac
done

pkgs(){
    cmd=$1
    echocmd=$2
    estimator=$3
    # Oh nooo... The estimator...
    if command -v "$cmd" >/dev/null 2>&1; then
        count=$(eval "$estimator")
        if [ -n "$count" ] && [ "$count" -ne 0 ]; then
            pkgc="${pkgc}${echocmd} [${count}], "
        fi
    fi
}

pkgm(){
    pkgc=""
    pkgs "pacman" "pacman" "pacman -Qq | wc -l"
    if command -v dpkg >/dev/null 2>&1 && command -v apt >/dev/null 2>&1; then
        pkgc="${pkgc}apt [$(dpkg --get-selections | grep -v deinstall | wc -l)], "
    fi
    pkgs "dnf" "dnf" "rpm -qa | wc -l"
    pkgs "zypper" "zypper" "rpm -qa | wc -l"
    #pkgs "apk" "apk" "grep -c '^P:' /lib/apk/db/installed"
    pkgs "apk" "apk" "grep -c '^P:' /lib/apk/db/installed 2>/dev/null || apk info | wc -l"
    pkgs "xbps-install" "xbps" "xbps-query -l | wc -l"
    if command -v pkg >/dev/null 2>&1; then
        case "$(uname -s)" in
            "FreeBSD"|"DragonFly") pkgc="${pkgc}pkg [$(pkg query -a '%n' | wc -l | tr -d ' ')], " ;;
            "Darwin") pkgc="${pkgc}pkg [$(pkg list | wc -l | tr -d ' ')], " ;;
            "SunOS") pkgc="${pkgc}pkg [$(pkginfo | wc -l | tr -d ' ')], " ;;
            *) command -v getprop >/dev/null 2>&1 && pkgc="${pkgc}" || pkgc="${pkgc}pkg, " ;;
        esac
    fi
    pkgs "nix-store" "nix" "ls /nix/store | wc -l"
    pkgs "pkgtool" "pkgtool" "ls /var/log/packages | wc -l"
    pkgs "yum" "yum" "rpm -qa | wc -l"
    pkgs "emerge" "emerge" "qlist -I | wc -l"
    pkgs "prt-get" "prt-get" "pkginfo -i | wc -l"
    pkgs "scratch" "scratch" "ls /var/lib/scratchpkg/db/ | wc -l"
    pkgs "pkgin" "pkgin" "pkg_info | wc -l | tr -d ' '"
    pkgs "pkg_add" "pkg_add" "pkg_info | wc -l | tr -d ' '"
    pkgs "pkgman" "pkgman" "find /boot/system/packages /boot/home/config/packages -name \"*.hpkg\" | wc -l"
    pkgs "kiss" "kiss" "ls /var/db/kiss/installed | wc -l"
    pkgs "flatpak" "flatpak" "flatpak list | wc -l"
    pkgs "snprt" "snprt" "ls /var/db/snprt/list/ | wc -l"
    pkgs "cave" "paludis" "ls /var/db/paludis/repositories/installed/data | wc -l"
    pkgs "eopkg" "eopkg" "ls /var/lib/eopkg/package | wc -l"
    pkgs "Compile" "compile" "ls /Programs | wc -l"
    pkgs "mine" "mine" "mine -q | wc -l"
    pkgs "inary" "inary" "ls /var/lib/inary/package -1 | wc -l"
    pkgs "tce" "tce" "tce-status -i | wc -l"
    [ -n "$pkgc" ] && pkgc=${pkgc%??}
    echo "$pkgc"
}

proch(){
    if command -v pgrep >/dev/null 2>&1; then
        pgrep -x $1 >/dev/null 2>&1
    else
    # i did it cuz minix3 dont have pgrep etc.
        ps -e | awk '{print $4}' | grep -qi "^$1$" >/dev/null 2>&1
    fi
}

env() {
    if [ -n "$XDG_CURRENT_DESKTOP" ]; then echo "$XDG_CURRENT_DESKTOP"
    elif [ -n "$DESKTOP_SESSION" ]; then echo "$DESKTOP_SESSION"
    elif proch "xfce4-session"; then echo "xfce"
    elif proch "kdeinit5"; then echo "kde"
    elif proch "gnome-session"; then echo "gnome"
    elif proch "lxsession"; then echo "lxqt"
    elif proch "mate-session"; then echo "mate"
    elif proch "sway"; then
    sway --version 2>/dev/null | grep -q 'swayfx' && echo "swayfx" || echo "sway"
    elif proch "hyprland"; then echo "hyprland"
    elif proch "dwm"; then echo "dwm"
    elif proch "dwl"; then echo "dwl"
    elif proch "twm"; then echo "twm"
    elif proch "i3"; then echo "i3"
    elif proch "bspwm" ; then echo "bspwm"
    elif proch "herbstluftwm"; then echo "herbstluftwm"
    elif proch "xmonad"; then echo "xmonad"
    elif proch "niri-session"; then echo "niri"
    elif command -v getprop >/dev/null 2>&1; then echo "surfaceflinger"
    elif [ "$(uname -s)" = "Haiku" ]; then echo "tracker"
    elif proch "kwin_x11"; then echo "kwin"
    elif proch "awesome"; then echo "awesome"
    elif proch "fluxbox"; then echo "fluxbox"
    elif proch "openbox"; then echo "openbox"
    elif proch "icewm"; then echo "icewm"
    else echo "$(tty)"
    fi
}

ramd(){
    case "$UNAME" in
        FreeBSD|DragonFly)
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(($(sysctl -n vm.stats.vm.v_wire_count) * pagesi / 1024 / 1024))"
        activm=$(($(sysctl -n vm.stats.vm.v_active_count) * pagesi / 1024 / 1024))
        inactm=$(($(sysctl -n vm.stats.vm.v_inactive_count) * pagesi / 1024 / 1024))
        usedm=$((wiredm + activm + inactm))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
        ;;
        OpenBSD|NetBSD)
        # i dont know how to make it work T_T
        pagesi="$(sysctl -n hw.pagesize)"
        wiredm="$(vmstat -s | grep "pages wired" | awk '{print $1}')"
        activm=$(vmstat -s | grep "pages active" | awk '{print $1}')
        usedm=$(((wiredm + activm) * pagesi / 1024 / 1024))
        physm=$(($(sysctl -n hw.physmem) / 1024 / 1024))
        echo "${usedm}MiB / ${physm}MiB"
        ;;
        Haiku)
        totalmem="$(($(vmstat | grep "max memory" | awk '{print int($3 / 1024 / 1024)}')))"
        usedmem="$(((totalmem - $(vmstat | grep "free memory" | awk '{print int($3 / 1024 / 1024)}'))))"
        echo "${usedmem}MiB / ${totalmem}MiB"
        ;;
        SunOS)
        memtot="$(prtconf | grep Memory | awk '{print $3}')"
        memavb="$(vmstat | awk 'NR==3 {print int($5 / 1024)}')"
        memusd="$((memtot - memavb))"
        echo "${memusd}MiB / ${memtot}MiB"
        ;;
        *)
        # i made it cuz environmentingonment bot doesn't have free command
        memtot="$(($(cat /proc/meminfo | awk 'NR==1 {print $2}') / 1024))"
        memavb="$(cat /proc/meminfo | awk 'NR==3 {print $2}')"
        memusd="$((memtot - (memavb / 1024)))"
        echo "${memusd}MiB / ${memtot}MiB"
        #free | awk 'NR==2 {print int($3 / 1024)"MiB" " / " int($2 / 1024)"MiB"}'
        ;;
    esac
}

cpug(){
    case "$UNAME" in
        FreeBSD|DragonFly) sysctl -n hw.model ;;
        OpenBSD|NetBSD) sysctl -n hw.model 2>/dev/null ;;
        Minix) grep 'model name' /proc/cpuinfo | awk '{print $3}' ;;
        Haiku) sysinfo -cpu | awk -F '\"' '/CPU #0/ {print $2}' ;;
        SunOS) kstat -p cpu_info:0:*:brand | awk -F'\t' '{print $2}' ;;
        *) if command -v getprop >/dev/null 2>&1; then
           #     cat /proc/cpuinfo | grep -i 'hardware' | awk -F ': ' '{print $2}'
                getprop ro.hardware
           else
                grep -m 1 'model name' /proc/cpuinfo | cut -d ':' -f2 | sed 's/^ //'
           fi
    esac
}

disk(){
    if command -v getprop >/dev/null 2>&1; then
        df /data -h | awk 'NR==2 {print $3 " / " $2}'
    elif [ "$(uname -s)" = "Haiku" ]; then
        disktotal="$(df /boot | grep "Total Blocks" | awk '{print int($3)}')"
        diskused="$(((disktotal - $(df /boot | grep "Free Blocks" | awk '{print int($3)}'))))"
        echo "${diskused}GiB / ${disktotal}GiB"
    else
        df -h / | awk 'NR==2 {print $3 " / " $2}' 
    fi
}

case "$ascii" in
    [Ee]ndeavour[Oo][Ss]*)
        ascia="${reset}                       "
        ascib="${red}           /${purple}o${blue}.         "
        ascic="${red}         /${purple}sssso${blue}-       "
        ascid="${red}       /${purple}ossssssso${blue}:     "
        ascie="${red}     /${purple}ssssssssssso${blue}+    "
        ascif="${red}   /${purple}ssssssssssssssso${blue}+  "
        ascig="${red} //${purple}osssssssssssssso${blue}+-  "
        ascih="${blue}  \`+++++++++++++++-\`   "
        ascij="                       "
        color="$purple"
        ;;
    [Mm]int*)
        ascia="${green}  ___________   "
        ascib="${green} |_          \\\  "
        ascic="${green}   | ${reset}| _____${green} |  "
        ascid="${green}   |${reset} | | | | ${green}|  "
        ascie="${green}   |${reset} | | | | ${green}|  "
        ascif=" ${green}  |${reset} \\\_____/ ${reset}${green}|  "
        ascig="${green}   \\\_________/  "
        ascih="                "
        ascij="                "
        color="$green"
        ;;
    [Ss]lackware*)
        ascia="${blue}    ________   "
        ascib="${blue}   /  ______|  "
        ascic="${blue}   | |______   "
        ascid="${blue}   \\\______  \\\  "
        ascie="${blue}    ______| |  "
        ascif="${blue} | |________/  "
        ascig="${blue} |____________ "
        ascih="               "
        ascij="               "
        color="$blue"
        ;;
    [Aa]rch*)
        ascia="                 " 
        ascib="${lblue}       /\\\        "
        ascic="${lblue}      /  \\\       "
        ascid="${lblue}     /.   \\\      "
        ascie="${lblue}    /      \\\     "
        ascif="${lblue}   /   ,,   \\\    "
        ascig="${lblue}  /   |  |  '\\\   "
        ascih="${lblue} /_-''    ''-_\\\  "
        ascij="                 "
        color="$lblue"
        ;;
    [Nn]ix[Oo][Ss]*)
        ascia="                 "
        ascib="${lblue}    \\\\\\\  \\\\\\\ //    "
        ascic=" ${lblue}  ==\\\\\\\__\\\\\\\/ //  "
        ascid="${lblue}     //   \\\\\\\//   "
        ascie="${lblue}  ==//     //==  "
        ascif="${lblue}   //\\\\\\\___//     "
        ascig="${lblue}  // /\\\\\\\  \\\\\\\==   "
        ascih="${lblue}    // \\\\\\\  \\\\\\\    " 
        ascij="                "
        color="$lblue"
        ;;
    [Vv]oid*)
        ascia="${green}     ________    "
        ascib="${green}   _ \\\_____  \`.  " 
        ascic="${green}  | \\\  ___ \`. |  " 
        ascid="${green}  | | /   \\\ | |  "
        ascie="${green}  | | \\\___/ | |  "
        ascif="${green}  | '._____ \\\_|  "
        ascig="${green}  '._______\\\     "
        ascih="${green}                 "
        ascij="${green}                 "
        color="$green"
        ;;
    [Uu]buntu*)
        ascia="              "
        ascib="${red}          _   "
        ascic="${red}      ---(_)  "  
        ascid="${red}  _/  ---  \\\  "
        ascie="${red} (_) |   |    "
        ascif="${red}   \\\  --- _/  "
        ascig="${red}      ---(_)  "
        ascih="              "
        ascij="              "
        color="$red"
        ;;
    [Dd]ebian*)
        # i made this ascii by myself
        ascia="${red}      _,_     "
        ascib="${red}   .:'\`\`\`':.  "
        ascic="${red}  ::   _  ':  " 
        ascid="${red}  ::  :   .:  "
        ascie="${red}  ':   \`\"'\`   " 
        ascif="${red}   \`:,        "
        ascig="${red}     \`\":,     "
        ascih="${red}              "
        ascij="${red}              "
        color="$red"
        ;;
    [Aa]lpine*)
        ascia="                "
        ascib="${blue}     /\\\ /\\\      "
        ascic="${blue}    // \\\  \\\     "
        ascid="${blue}   //   \\\  \\\    "
        ascie="${blue}  //     \\\  \\\   "
        ascif="${blue} //       \\\  \\\  "
        ascig="${blue}           \\\  \\ "
        ascih="${blue}            \\\   "
        ascij="                "
        color="$blue"
        ;;
    [Ff]edora*)
        ascia="${blue}                 "
        ascib="${blue}         .###.   "
        ascic="${blue}        #'   '#  "
        ascid="${blue}        W     '  "
        ascie="${blue}   .w##A&##'     "
        ascif="${blue}  #'    M        "
        ascig="${blue}  #,   ,#        "
        ascih="${blue}  \`*###*'        "
        ascij="${blue}                 "
        color="$blue"
        ;;
    [Pp]ostmarket[Oo][Ss]*)
        ascia="              "
        ascib="${green}      /\\\      "
        ascic="${green}     /  \\\     "
        ascid="${green}     \\\_  \\\    "
        ascie="${green}   /\\\_ \\\/ _   "
        ascif="${green}  /  / __/ \\\  "
        ascig="${green} /___\\\ \\\____\\\ "
        ascih="              "
        ascij="              "
        color="$green"
        ;;
    [Cc][Rr][Uu][Xx]|[Kk][Ii][Ss][Ss]*)
        ascia="${blue}      ___     "
        ascib="${blue}     (${reset}..${blue} |    "
        ascic="${blue}     (${purple}<>${blue} |    "
        ascid="${blue}    / ${reset}__${blue}  \\\   "
        ascie="${blue}   ( ${reset}/  \\\\${blue} /|  "
        ascif="${blue}  ${purple}_${blue}/\\\\${reset} __)${blue}/${purple}_${blue})  "
        ascig="${blue}  ${purple}\\\/${blue}-____${purple}\\\/   "
        ascih="              "
        ascij="              "
        color="$blue"
        ;;
    [Oo]pen[Ss][Uu][Ss][Ee]*)
        ascia="${green}     _______    "
        ascib="${green}  __|    __ \\\   "
        ascic="${green} |      / .\\\ \\\  "
        ascid="${green} |      \\\__/ |  "
        ascie="${green} |    _______|  "
        ascif="${green} |    \\\_______  "
        ascig="${green} |___________/  "
        ascih="${green}                "
        ascij="${green}               "
        color="$green"
        ;;
    [Ll]ocoware*)
        ascia="              "
        ascib="              "
        ascic="${yellow}       dMP    "
        ascid="${yellow}      dMP     "
        ascie="${yellow}     dMP      "
        ascif="${yellow}    dMP       "
        ascig="${yellow}   dMMMMMMP   "
        ascih="              "
        ascij="              "
        color="$yellow"
        ;;
    [Aa]rtix*)
        ascia="                "
        ascib="${lblue}       /\\\       "
        ascic="${lblue}      /  \\\      "
        ascid="${lblue}     /\`'.,\\\     "
        ascie="${lblue}    /     ',    "
        ascif="${lblue}   /      ,\`\\\   "
        ascig="${lblue}  /   ,.'\`.  \\\  "
        ascih="${lblue} /.,'\`     \`'.\\\ "
        ascij="                "
        color="$lblue"
        ;;
    [Dd]evuan*)
        ascia="                "
        ascib="${yellow}   ..:::.       "
        ascic="${yellow}      ''===-    "
        ascid="${yellow}          '+#;  "
        ascie="${yellow}           =##  "
        ascif="${yellow}       .+:##;   "
        ascig="${yellow}  .:=+###:*'    "
        ascih="${yellow}  '####='       "
        ascij="                "
        color="$yellow"
        ;;
    [Ff]ree[Bb][Ss][Dd]|[Hh]ellosystem*)
        ascia="                 "
        ascib="${red}  /\\\,-'''''-,/\\\  "
        ascic="${red}  \\\_)       (_/  "
        ascid="${red}  |           |  "
        ascie="${red}  |           |  "
        ascif="${red}   ;         ;   "
        ascig="${red}    '-_____-'    "
        ascih="                 "
        ascij="                 "
        color="$red"
        ;;
    [Gg]entoo*)
        ascia="${purple}   _-----_     "
        ascib="${purple}  (       \\\    "
        ascic="${purple}  \\\    0   \\\   "
        ascid="${reset}   \\\        )  "
        ascie="${reset}   /      _/   "
        ascif="${reset}  (     _-     "
        ascig="${reset}  \\\____-       "
        ascih="               "
        ascij="               "
        color="$purple"
        ;;
    [Aa]ndroid*)
        ascia="                     "
        ascib="${green}   ;,           ,;   "
        ascic="${green}    ';,.-----.,;'    "
        ascid="${green}   ,'           ',   "
        ascie="${green}  /    O     O    \\\  "
        ascif="${green} |                 | "
        ascig="${green} '-----------------' "
        ascih="                     "
        ascij="                     "
        color="$green"
        ;;
    [Cc]achy[Oo][Ss]*)
        ascia="${aqua}    .''''''''''''/    "
        ascib="${aqua}   /      ______/     "
        ascic="${aqua}  /      /            "
        ascid="${aqua} /      /             "
        ascie="${aqua} \\\      \\\             "
        ascif="${aqua}  \\\      \\\___________ "
        ascig="${aqua}   \\\                / "
        ascih="${aqua}    '..............'  "
        ascij="                     "
        color="$aqua"
        ;;
    [Pp]op!_[Oo][Ss]|[Pp]op_[Oo][Ss]*)
        ascia="${aqua}  ______             "
        ascib="${aqua}  \\\   _ \\\        __  "
        ascic="${aqua}   \\\ \ \\\ \\\      / /  "
        ascid="${aqua}    \\\ \\\_\\\ \\\    / /   "
        ascie="${aqua}     \\\  ___\\\  /_/    "
        ascif="${aqua}      \\\ \\\    _       " 
        ascig="${aqua}     __\\\ \\\__(_)_     "
        ascih="${aqua}    (___________)    "
        ascij="                   "
        color="$aqua"
        ;;
    [Oo]pen[Bb][Ss][Dd]*)
        ascia="${yellow}        _____      "
        ascib="${yellow}      \\\-     -/    "
        ascic="${yellow}   \\\_/         \\\   "
        ascid="${yellow}   |        ${reset}O O${yellow} |  "
        ascie="${yellow}   |_  <   )  3 )  "
        ascif="${yellow}   / \\\         /   "
        ascig="${yellow}      /-_____-\\\    "
        ascih="${yellow}                   "
        ascij="                  "
        color="$yellow"
        ;;
    [Cc]ent[Oo][Ss]*)
        ascia="               "
        ascib="   ${green}____${yellow}^${purple}____   "
        ascic="   ${green}|\\\  ${yellow}|${purple}  /|   "
        ascid="   ${green}| \\\ ${yellow}|${purple} / |   "
        ascie="  ${purple}<---- ${lblue}---->  "
        ascif="   ${lblue}| / ${green}|${yellow} \\\ |   "
        ascig="   ${lblue}|/__${green}|${yellow}__\\\|   "
        ascih="       ${green}v       "
        ascij="               "
        color="$green"
        ;;
    [Nn]et[Bb][Ss][Dd]*)
        ascia="  \\\\\\\\${red}\`-______,----__    "
        ascib="   \\\\\\\ ${red}       __,---\`_  "
        ascic="    \\\\\\\ ${red}      \`.____    "
        ascid="     \\\\\\\\${red}-______,----\`-  "
        ascie="      \\\\\\\               "
        ascif="       \\\\\\\              "
        ascig="        \\\\\\\             "
        ascih="         \\\\\\\            "
        ascij="                     "
        color="$red"
        ;;
    [Hh]aiku*)
        ascia="${green}         ,^,         "
        ascib="${green}        /   \\\        "
        ascic="${green}  *--_ ;     ; _--*  "
        ascid="${green}  \\\   '\"     \"'   /  "
        ascie="${green}   '.           .'   "
        ascif="${green}  .-'\"         \"'-.  "
        ascig="${green}   '-.__.   .__.-'   "
        ascih="${green}         |_|         "
        ascij="                     "
        color="$green"
        ;;
    [Vv]enom*)
        ascia="${gray}  ,__   _,.,_       "
        ascib="${gray}  ':###:\"'\`'\"#:.    "
        ascic="${gray}    :####.    '#:   "
        ascid="${gray}   :#: '####.  :#:  "
        ascie="${gray}    :#.   '###.#:   "
        ascif="${gray}     '#:,,_,,:###:  "
        ascig="${gray}       \`''=''\` '^:  "
        ascih="                    "
        ascij="                   "
        color="$gray"
        ;;
    [Cc]himera*)
        ascia="${blue}  ,.....,${red} ,        "
        ascib="${blue}  |     |${red} |        "
        ascic="${blue}  |   ,-'${red} |        "
        ascid="${blue}  '---\`${red}.'\`\` _____  "
        ascie="${purple}  .---,${red}'._.',---.  "
        ascif="${purple}  |   \`-,${red} ,-\`   |  "
        ascig="${purple}  |     | ${red}|     |  "
        ascih="${purple}  '\"\"\"\"\"'${red} '\"\"\"\"\"'  "
        ascij="                   "
        color="$purple"
        ;;
    [Oo]pen[Ii]ndiana*)
        ascia="                  "
        ascib="          *       "
        ascic="${blue}    .-\`-.${reset} |       "
        ascid="${blue}    |   | ${reset}|-'-.   "
        ascie="${blue}    \\\   / ${reset}|  .'   "
        ascif="  .' ${blue}\`\"\` ${reset}_.-\`     "
        ascig="  '-..-'\`         "
        ascih="                  "
        ascij="                  "
        ;;
    [Ee]xherbo*)
        ascia=" .'.  ,_....,__.._  "
        ascib="  \\\ |'        \`'. | "
        ascic="  /'   _   /${blue}w${reset}\\\   \\\. "
        ascid=" :    |${blue}#${reset}|  \\\\${blue}#${reset}/    : "
        ascie=" :   ${red}.-*\"\"\"=-_    ${reset}| "
        ascif="  \\\ ${red}|${reset}  +    B ${red}':${reset} /  "
        ascig="   '.${red}'._____.-'${reset} /   "
        ascih="     ${reset}'=.,,,,,.='    "
        ascij="                    "
        color="$blue"
        ;;
    [Oo]barun*)
        ascia="${blue}       __.     "
        ascib="${blue}    .W'        "
        ascic="${blue}   //    .ww.  "
        ascid="${blue}  ||    WWWW*  "
        ascie="${blue}  ||    www/   "
        ascif="${blue}  \\\|._  ,//    "
        ascig="${blue}   '^4WP^'     "
        ascih="               "
        ascih="               "
        color="$blue"
        ;;
    [Bb]edrock*)
        ascia="               "
        ascib="${gray}   _________   "
        ascic="${gray}  | ${reset}__      ${gray}|  "
        ascid="${gray}  | ${reset}\\\ \\\___  ${gray}|  "
        ascie="${gray}  |  ${reset}\\\  _ \\\ ${gray}|  "
        ascif="${gray}  |   ${reset}\\\___/${gray} |  "
        ascig="${gray}  |_________|  "
        ascih="               "
        ascij="               "
        color="$gray"
        ;;
    [Ss]olus*)
        ascia="  ${gray}    _${reset}/\\\\${gray}<^^>-._     "
        ascib="  ${gray}  .'${reset}/  \\\ ${gray}     '.   "
        ascic="  ${gray} / ${reset}/    \\\ ${gray}      \\\  "
        ascid="  ${gray}:${reset} /      ||'.,_${gray}  : "
        ascie="  ${gray}:${reset}/       |]_.\\\_\`:> "
        ascif="  ${reset}<.-----^^''${blue}_,:-=${gray}/  "
        ascig="  ${blue}  ':-=*^''\` ${blue}  .'   "
        ascih="  ${blue}    \`^<.__.>^\`     "
        ascij="                          "  
        color="$blue"
        ;;
    [Dd]ragon[Ff]ly*)
        ascia="     ,${red}_${reset},     "
        ascib="  ('-_${red}|${reset}_-')  "
        ascic="   >--${red}|${reset}--<   "
        ascid="  (_-'${red}|${reset}'-_)  "
        ascie="      ${red}|      "
        ascif="      ${red}|      "
        ascig="      ${red}|      "
        ascih="             "
        ascij=""
        color="$red"
        ;;
    [Gg]obo*)
        ascia="            "
        ascib="${lblue}    _____   "
        ascic="${lblue}   / ____|  "
        ascid="${lblue}  | |  __   "
        ascie="${lblue}  | | |_ |  "
        ascif="${lblue}  | |__| |  "
        ascig="${lblue}   \\\_____|  "
        ascih="            "
        ascij="            "
        color="$lblue"
        ;;
    [Tt]2/[Ll]inux*)
        ascia="${blue}                "
        ascib="${blue} TTTTTTTTTT     "
        ascic="${blue}     tt${reset}   222   "
        ascid="${blue}     tt${reset}  2   2  "
        ascie="${blue}     tt${reset}     2   "
        ascif="${blue}     tt${reset}    2    "
        ascig="${blue}     tt${reset}  22222  "
        ascih="${blue}                "
        ascij="${blue}                "
        color="$blue"
        ;;
    [Pp]arabola*)
        ascia="                  "
        ascib="${purple}   __ __ __  _    "
        ascic="${purple} .\`_//_//_/ / \`.  "
        ascid="${purple}           /  .\`  "
        ascie="${purple}          / .\`    "
        ascif="${purple}         /.\`      "
        ascig="${purple}        /\`        "
        ascih="${purple}                  "
        ascij="${purple}                  "
        color="$purple"
        ;;
    [Ss]ulin[Oo][Ss]*)
        ascia="    it's donkey  "
        ascib="                 "
        ascic="${gray} ^__^            "
        ascid="${gray} (${reset}oo${gray})\\\_______    "
        ascie="${gray} (__)\\\       )\\\  "
        ascif="${gray}     ||-----||   "
        ascig="${gray}     ||     ||   "
        ascih="                 "
        ascij="                 "
        color="$gray"
        ;;
    [Oo]mni[Oo][Ss]*)
        ascia="${reset}    _____       "
        ascib="${reset}   / ___ \\\      "
        ascic="${reset}  | /  ${yellow}_${reset}\\\\${yellow}_${reset}|${yellow}_    "
        ascid="${reset}  | \\\_${yellow}/ ___ \\\   "
        ascie="${reset}   \\\_${yellow}| /${reset}_/${yellow} \\\ |  "
        ascif="${yellow}     | \\\___/ |  "
        ascig="${yellow}      \\\_____/   "
        ascih="                "
        ascij="                "
        color="$yellow"
        ;;
    [Tt]iny[Cc]ore*)
        ascia="${gray}                "
        ascib="${gray}    ,.-'''-.,   "
        ascic="${gray}   /       .'\\\  "
        ascid="${gray}  |      ,'   | "
        ascie="${gray}  |    ,'     | "
        ascif="${gray}   \\\.,'      /  "
        ascig="${gray}    \`'-...-'\`   "
        ascih="${gray}                "
        ascij="${gray}                "
        color="$gray"
        ;;
    *)
        ascia="     ___     "
        ascib="    (.. |    "
        ascic="    (<> |    "
        ascid="   / __  \\\   "
        ascie="  ( /  \\\ /|  "
        ascif=" _/\\\ __)/_)  "
        ascig=" \\\/-____\\\/   "
        ascih="             "
        ascij="             "
        ;;
esac

printf "\n"
printf "%s$ascia $reset ${color}$(userg)${reset}@${color}$host${reset} \n"
printf "%s$ascib $reset ${color}os:${reset}     $(distrog)\n"
printf "%s$ascic $reset ${color}pkg:${reset}    $(pkgm)\n"
printf "%s$ascid $reset ${color}ram:${reset}    $(ramd)\n"
printf "%s$ascie $reset ${color}cpu:${reset}    $(cpug)\n"
printf "%s$ascif $reset ${color}sh:${reset}     $shell\n"
printf "%s$ascig $reset ${color}env:${reset}    $(env)\n"
printf "%s$ascih $reset ${color}disk:${reset}   $(disk)\n"
printf "%s$ascij$reset\n"
